table 'D - Stocks'
	lineageTag: c442708f-d091-4fe7-b4f9-7b2e83e520d7

	column shortName
		dataType: string
		lineageTag: b3291d87-deda-4dd4-9d4e-dc4d13cf3393
		summarizeBy: none
		sourceColumn: shortName

		annotation SummarizationSetBy = Automatic

	column longName
		dataType: string
		lineageTag: 32144d52-83c7-4a92-8090-b714597dcd20
		summarizeBy: none
		sourceColumn: longName

		annotation SummarizationSetBy = Automatic

	column symbol
		dataType: string
		lineageTag: 100ba296-cfa3-414e-b0ac-68c4aa1eddc5
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column logourl
		dataType: string
		lineageTag: 87210e8a-6bda-418c-8f9c-a1952d88a5e5
		summarizeBy: none
		sourceColumn: logourl

		annotation SummarizationSetBy = Automatic

	column ticker
		dataType: string
		lineageTag: c0d865ee-76b4-4085-8f4a-a396bf442fea
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column marketCap
		dataType: double
		lineageTag: 74724a1e-b219-4310-9980-e749d42aaf5c
		summarizeBy: sum
		sourceColumn: marketCap

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'D - Stocks' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost:5432", "inv"),
				    public_stock_info = Fonte{[Schema="public",Item="stock_info"]}[Data],
				    #"Colunas Removidas" = Table.RemoveColumns(public_stock_info,{"currency", "index", "regularMarketChange", "regularMarketChangePercent", "regularMarketTime", "regularMarketPrice", "regularMarketDayHigh", "regularMarketDayRange", "regularMarketDayLow", "regularMarketVolume", "regularMarketPreviousClose", "regularMarketOpen", "fiftyTwoWeekRange", "fiftyTwoWeekLow", "fiftyTwoWeekHigh", "priceEarnings", "earningsPerShare"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

