table 'F - Historical Prices'
	lineageTag: 41d75066-7878-4d58-8dcf-449442e62ac9

	column ticker
		dataType: string
		lineageTag: 4bc3c601-3b19-4c40-aa8e-2dad76692f70
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2b13dd49-2243-40fa-b656-6217a788ae7e
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column open
		dataType: double
		lineageTag: c66ef64b-951c-4ee2-beaf-33625c5f5603
		summarizeBy: sum
		sourceColumn: open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column close
		dataType: double
		lineageTag: e3a4ada4-f4fc-43ba-8502-c8a223d062cb
		summarizeBy: sum
		sourceColumn: close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column low
		dataType: double
		lineageTag: 38735408-fb6c-4f74-9377-52f0c8c12c89
		summarizeBy: sum
		sourceColumn: low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column high
		dataType: double
		lineageTag: 123da06e-af0e-4d23-a229-52bfe49b2867
		summarizeBy: sum
		sourceColumn: high

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column volume
		dataType: double
		formatString: 0
		lineageTag: 8076c553-e726-4636-ac0d-eb0d632b6450
		summarizeBy: sum
		sourceColumn: volume

		annotation SummarizationSetBy = Automatic

	column adjustedclose
		dataType: double
		lineageTag: 77bf91fe-dd87-421d-914c-8177824d9b12
		summarizeBy: sum
		sourceColumn: adjustedclose

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column loaded_at
		dataType: dateTime
		formatString: Long Date
		lineageTag: c6477a11-eb86-4d1d-8bf3-aad481bf80cc
		summarizeBy: none
		sourceColumn: loaded_at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'F - Historical Prices' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost:5432", "inv"),
				    public_stock_quotes_history = Fonte{[Schema="public",Item="stock_quotes_history"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(public_stock_quotes_history,{{"date", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

